### ISSUE TITLE
About the '@@@@@@@' in contents

### ISSUE THREAD

**Issue by Edith-vis** [MELALab/nela-gt#1]
I have read your paper 'NELA-GT-2020: A Large Multi-Labelled News Dataset for The Study of Misinformation in News Articles' and downloaded the dataset from https://doi.org/10.7910/ DVN/CHMUYZ. I found that each article has ‘@@@@@@@’ popped up instead of normal words which brings great trouble for research. Can I have the true context of every news article? By the way, can I know what keyword dataset did you use to get the 2020 U.S. Presidential Election subset?

**Comment by mgruppi** [comment]
Hi. Unfortunately, we cannot provide the unmodified version of the dataset at the moment.
