### ISSUE TITLE
Keywords used for the 2020 election split

### ISSUE THREAD

**Issue by MexicanLemonade** [MELALab/nela-gt#6]
Thanks for your work!
I'm trying to base my study on your valuable corpus and found your keywords provided to filter the two subsets in the 2021 corpus helpful. 
I'm wondering if you could provide the keywords you used to filter the 2020 covid/election subsets, like the ones you provided in the 2021 version. I found the 2021 covid keywords all-encompassing while the 2021 capital riot keywords very limiting to that event.
If you still have that, could you please share the file? I'll really appreciate it:)

**Comment by mgruppi** [comment]
Hello. We've added the list of keywords to the dataverse. Please check out the dataset page: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/CHMUYZ
